In [74]:
#READ DATA FROM CSV AND HOW TO WRITE THR DATA INTO CSV

In [75]:
#create text file, data enter |write operation
with open("Student.txt","w") as file:
  file.write("Name, Department, Marks, City \n"),
  file.write("Astik, CSE, 85, AGRA \n"),
  file.write("Abhiyanm, IT, 88, MATHURA \n"),
  file.write("Aditya, CSE, 98, NOIDA \n"),
  file.write("Ayaansh, IT, 80, HATHRAS")

In [76]:
#reading the txt file
with open("Student.txt","r") as file:
  data=file.read()
  print(data)

Name, Department, Marks, City
Astik, CSE, 85, AGRA
Abhiyanm, IT, 88, MATHURA
Aditya, CSE, 98, NOIDA
Ayaansh, IT, 80, HATHRAS

##SAVE the.txt DATA into .CSV file

In [77]:
import pandas as pd
df = pd.read_csv('Student.txt', skipinitialspace=True)#read the file
df.to_csv('Student.csv', index=True)#conversion
df

       Name Department  Marks     City
0     Astik        CSE     85     AGRA
1  Abhiyanm         IT     88  MATHURA
2    Aditya        CSE     98    NOIDA
3   Ayaansh         IT     80   HATHRAS

In [78]:
#JSON FILE

In [79]:
#excel

In [80]:
#picke
#.pkl
df_pickle=pd.DataFrame({
    "Name":["AMAN","AJAY","RAKESH","GEETA"],
    "Marks":[80,90,50,40]
})

In [81]:
df_pickle

     Name  Marks
0    AMAN     80
1    AJAY     90
2  RAKESH     50
3   GEETA     40

In [82]:
#save the dataframe into pickle
df.to_pickle("studen_pkl.pkl")

In [83]:
#read the pickle file
st=pd.read_pickle("studen_pkl.pkl")
st

       Name Department  Marks     City
0     Astik        CSE     85     AGRA
1  Abhiyanm         IT     88  MATHURA
2    Aditya        CSE     98    NOIDA
3   Ayaansh         IT     80   HATHRAS

##WEB SCRAPPING

In [84]:
import requests
from bs4 import BeautifulSoup
url="https://www.amazon.in/"
page=requests.get(url)
soup= BeautifulSoup(page.text, "html.parser")

In [85]:
print(soup.title.text)

Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in

##PARQUET
-TO CONVERT ROW ORIENED DATA INTO COL ORIECNTED

In [86]:
df_parquet=df_pickle

In [87]:
df_parquet

     Name  Marks
0    AMAN     80
1    AJAY     90
2  RAKESH     50
3   GEETA     40

In [88]:
df_parquet.to_parquet("student_pqt.parquet", index=False)

In [89]:
#read the parquet file
df_parquet_file=pd.read_parquet("student_pqt.parquet")

In [90]:
print(df_parquet)

     Name  Marks
0    AMAN     80
1    AJAY     90
2  RAKESH     50
3   GEETA     40

##SQLITE

In [91]:
import sqlite3
conn=sqlite3.connect("students.db")

In [92]:
cursor=conn.cursor()
print("Database Created Successfully")

Database Created Successfully

In [93]:
cursor.execute("""
    Create TABLE IF NOT EXISTS students_table(
    Name TEXT,
    ROLL_No INTEGER,
    Marks INTEGER)
    """
)
print("Table is created successfully")

Table is created successfully

In [94]:
#write data into table
import sqlite3
conn = sqlite3.connect("students.db")
cursor = conn.cursor()

cursor.execute(
    "INSERT INTO students_table VALUES(?, ?, ?)",
    ("Amit", 101, 90)
)
cursor.execute(
    "INSERT INTO students_table VALUES('Aman', 102, 95)"
)
cursor.execute(
    "INSERT INTO students_table VALUES('Ayaansh', 123, 98)"
)

In [95]:
conn.commit()
print("Records inserted successfully !!")
conn.close()

Records inserted successfully !!

In [96]:
#retrieve | read the data
conn=sqlite3.connect("students.db")
cursor=conn.cursor()
cursor.execute("SELECT * FROM students_table")
rows=cursor.fetchall()
for row in rows:
  print(row)
conn.close()

('Amit', 101, 90)
('Aman', 102, 95)
('Ayaansh', 123, 98)